<?php
/*数据库配置*/
define('DB_HOST','127.0.0.1');//数据库连接地址，默认：localhost或127.0.0.1
define('DB_PORT','3306');//数据库端口
define('DB_USER','');//数据库账号
define('DB_PASSWD','');//数据库密码
define('DB_NAME','cshj123');//数据库名称
define('DB_PRE','ymdl_');//数据库前缀
define('HT_USER','');//后台账号
define('HT_PASS','');//后台密码
?>
